### ISSUE TITLE
benchmark_v2/str_locality_benchmark.py throws errors

### ISSUE THREAD

**Issue by ajpotts** [Bears-R-Us/arkouda#3797]
**Describe the bug**
When I run make benchmark size=10 on my local linux box, I get the following errors:
```
--- Logging error ---
Traceback (most recent call last):
  File "/home/amandapotts/anaconda3/envs/arkouda-dev/lib/python3.12/logging/__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/amandapotts/git/arkouda/arkouda/pdarrayclass.py", line 376, in __del__
    logger.debug(f"deleting pdarray with name {self.name}")
Message: 'deleting pdarray with name id_q7pl9AR_3'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/amandapotts/anaconda3/envs/arkouda-dev/lib/python3.12/logging/__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/amandapotts/git/arkouda/arkouda/pdarrayclass.py", line 376, in __del__
    logger.debug(f"deleting pdarray with name {self.name}")
Message: 'deleting pdarray with name id_q7pl9AR_6'
Arguments: ()
```

**Comment by ajpotts** [comment]
Setting `setuptools==66.1.1` removes the `DeprecationWarning: pkg_resources is deprecated as an API.`   As discussed here:
https://stackoverflow.com/questions/76043689/pkg-resources-is-deprecated-as-an-api

**Comment by ajpotts** [comment]
The bug seems to originate at the global variable updates here:
https://github.com/Bears-R-Us/arkouda/blob/master/benchmark_v2/str_locality_benchmark.py#L40
and here:
https://github.com/Bears-R-Us/arkouda/blob/master/benchmark_v2/str_locality_benchmark.py#L44

The error disappears with the use of the pytest `-s` flag:
`python3 -m pytest -c benchmark.ini --benchmark-autosave --benchmark-storage=file://benchmark_v2/.benchmarks --size=10 -s`
This flag disables all capturing:
https://docs.pytest.org/en/stable/how-to/capture-stdout-stderr.html

**Comment by ajpotts** [comment]
Here is a related PR: https://github.com/Bears-R-Us/arkouda/pull/2279
